### ISSUE TITLE
CI never compiles the lib unit tests without features, so a feature-gated call in a plain #[cfg(test)] module ships broken

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/ferro-hgvs#1505]
Bare `cargo test` — the command `README.md` documents — has been broken on `main` since #1372, and no CI job could see it.

## Reproduced on `origin/main` (`a530cdaf`)

```
$ cargo test --no-run --lib
error[E0599]: no method named `parse_parallel` found for struct `processor::BatchProcessor<P>` in the current scope
error[E0599]: no method named `parse_streaming` found for struct `processor::BatchProcessor<P>` in the current scope
error[E0599]: no method named `parse_and_normalize_parallel` found for struct `processor::BatchProcessor<P>` in the current scope
error[E0599]: no method named `parse_and_normalize_streaming` found for struct `processor::BatchProcessor<P>` in the current scope
error: could not compile `ferro-hgvs` (lib test) due to 4 previous errors
```

`streaming_batch_matches_the_vec_api_exactly` (`src/batch/processor.rs:841`) sits in a plain `#[cfg(test)]` module but calls four methods from an `impl` block gated `#[cfg(feature = "parallel")]` (`:495`). #1504 fixes the instance by gating the test.

## Why CI cannot catch this class

Every test invocation in `ci.yml` either passes `--features dev` (which enables `parallel`) or is scoped to the integration binary:

| invocation | features | scope |
|---|---|---|
| `cargo nextest archive --features dev …` | `dev` | everything |
| `cargo nextest archive --cargo-profile soak --test it` | none | **`--test it` only** |

So the featureless build exists, but it only ever compiles `tests/it/`. **The lib unit tests are never compiled without features anywhere in CI.** A feature-gated call from an ungated `#[cfg(test)]` module in `src/**` is therefore invisible until a contributor runs the documented command.

That is what happened here: reported by an external contributor following `README.md:433`, not by the suite.

## Suggested shape

Add a cheap featureless compile of the lib tests to the existing build job — it needs no run, so it costs one `cargo test --no-run --lib`:

```yaml
- name: Lib tests compile without features
  run: cargo test --no-run --lib
```

Compile-only is the right scope: the point is that the *default* feature set builds, not that the gated tests run. Pair it with the existing `--test it` featureless archive and both halves of the test tree are covered.

Worth considering alongside: `README.md:433` tells a newcomer to run `cargo test`, while `CLAUDE.md` uses `cargo nextest run --features dev` throughout. If bare `cargo test` is meant to work, the guard above keeps it working; if it is not, the README should say which features to pass.
