### PR TITLE
ci: compile the default-feature unit tests so a gated call cannot ship

### LINKED ISSUE #1505: CI never compiles the lib unit tests without features, so a feature-gated call in a plain #[cfg(test)] module ships broken
Bare `cargo test` — the command `README.md` documents — has been broken on `main` since #1372, and no CI job could see it.

## Reproduced on `origin/main` (`a530cdaf`)

```
$ cargo test --no-run --lib
error[E0599]: no method named `parse_parallel` found for struct `processor::BatchProcessor<P>` in the current scope
error[E0599]: no method named `parse_streaming` found for struct `processor::BatchProcessor<P>` in the current scope
error[E0599]: no method named `parse_and_normalize_parallel` found for struct `processor::BatchProcessor<P>` in the current scope
error[E0599]: no method named `parse_and_normalize_streaming` found for struct `processor::BatchProcessor<P>` in the current scope
error: could not compile `ferro-hgvs` (lib test) due to 4 previous errors
```

`streaming_batch_matches_the_vec_api_exactly` (`src/batch/processor.rs:841`) sits in a plain `#[cfg(test)]` module but calls four methods from an `impl` block gated `#[cfg(feature = "parallel")]` (`:495`). #1504 fixes the instance by gating the test.

## Why CI cannot catch this class

Every test invocation in `ci.yml` either passes `--features dev` (which enables `parallel`) or is scoped to the integration binary:

| invocation | features | scope |
|---|---|---|
| `cargo nextest archive --features dev …` | `dev` | everything |
| `cargo nextest archive --cargo-profile soak --test it` | none | **`--test it` only** |

So the featureless build exists, but it only ever compiles `tests/it/`. **The lib unit tests are never compiled without features anywhere in CI.** A feature-gated call from an ungated `#[cfg(test)]` module in `src/**` is therefore invisible until a contributor runs the documented command.

That is what happened here: reported by an external contributor following `README.md:433`, not by the suite.

## Suggested shape

Add a cheap featureless compile of the lib tests to the existing build job — it needs no run, so it costs one `cargo test --no-run --lib`:

```yaml
- name: Lib tests compile without features
  run: cargo test --no-run --lib
```

Compile-only is the right scope: the point is that the *default* feature set builds, not that the gated tests run. Pair it with the existing `--test it` featureless archive and both halves of the test tree are covered.

Worth considering alongside: `README.md:433` tells a newcomer to run `cargo test`, while `CLAUDE.md` uses `cargo nextest run --features dev` throughout. If bare `cargo test` is meant to work, the guard above keeps it working; if it is not, the README should say which features to pass.

### PR DESCRIPTION
**Pull request by nh13**
Closes #1505.

> **Stacked on #1509** (base is `refactor/issue-1507-retire-parallel-gate`, not `main`). The guard added here is red on `main` today — that is the bug it guards against — so it cannot land first. Review #1509 first; this retargets to `main` automatically when that merges.

Every Rust job in `ci.yml` either passes `--features dev` / `--all-features`, or is scoped to the integration binary. So the default feature set's unit tests — the `#[cfg(test)]` modules under `src/` — are compiled **nowhere** in CI:

| invocation | features | scope |
|---|---|---|
| `cargo clippy --features dev --all-targets` | `dev` | everything |
| `cargo clippy --all-features --all-targets` | all | everything |
| `cargo nextest archive --features dev` | `dev` | everything |
| `cargo nextest archive --cargo-profile soak --test it` | **none** | `--test it` only |
| `cargo clippy --release` / `cargo build --release` | none | no test targets |

The featureless build exists, but only ever compiles `tests/it/`. A feature-gated call from an ungated `#[cfg(test)]` module in `src/**` is invisible until someone runs the documented command — which is how #1372's defect reached `main` and stayed there, found by an external contributor (#1504) rather than by the suite.

## The change

One step in the existing `build` job:

```yaml
- name: Unit tests compile with default features
  run: cargo test --no-run --lib --bins
```

- **`--no-run`** — the claim being defended is that the default feature set *builds*, not that these tests run a second time.
- **`--lib --bins`** — covers every `#[cfg(test)]` module under `src/`. The integration tree is already compiled featureless by `test-build-soak`, so the two together cover both halves.
- **In `build`, not a new job** — for the reason the release-profile lint immediately above it gives at length: the repository sits near the 10 GiB Actions cache cap and #1218 records eviction cascades from adding cache keys. `build` already owns `build-release` and is already a required check, so this blocks a merge rather than only reddening an optional job.

## It was verified to fire, not just to pass

A guard that passes proves nothing on its own. Restoring the pre-#1507 `src/batch/processor.rs` — the actual #1372 defect — and re-running the new step:

```
### guard on this branch
exit=0
### with main's gated impl block restored
exit=101          <- the guard fires
E0599 count: 5    <- the four original errors, plus the summary line
### restored
exit=0
```

`actionlint` passes on the modified workflow.

## Also

`README.md`'s Development block listed `cargo build` / `cargo test` / `cargo clippy` with no indication that they are the reduced feature set — the ambiguity #1505 flagged at the end. It now says so and points at the `--features dev` invocations CI actually runs. The bare commands stay correct, and this job is what keeps them that way.

### CODE REVIEW

**Comment by nh13** [comment]
@coderabbitai pause
